name: just_cook_bro
description: A smart cooking assistant powered by Gemini.
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  supabase_flutter: ^2.5.0
  purchases_flutter: ^8.0.0
  purchases_ui_flutter: ^8.0.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.0
  lucide_icons: ^0.257.0
  provider: ^6.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.0
  uuid: ^4.3.0
  http: ^1.2.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/